"use client";
import { useState } from "react";
import { AdminShell, Icon } from "../components/admin-shell";
import { assetUrl, useAdminApi } from "../lib/api";
type Buyer = { id: string; name: string; email: string; phone: string; address: string; profileImage?: string; orders: Array<{ _id: string; orderNumber: string; createdAt: string; items: unknown[]; status: string; total: number }> };
export default function BuyerManagementPage() { const { data: users, loading, error } = useAdminApi<Buyer[]>("/admin/users?role=buyer", []); const [selected, setSelected] = useState<Buyer | null>(null); const spent = selected?.orders.reduce((sum, o) => sum + o.total, 0) || 0;
  return <AdminShell title="User Management" subtitle="Manage registered users and view their order history."><section className="dashboard-card simple-users-card"><div className="simple-users-heading"><h2>All Users ({users.length})</h2></div><div className="table-scroll"><table className="simple-users-table"><thead><tr><th>User</th><th>Email</th><th>Phone</th><th>Address</th><th/></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><div style={{display:"flex",alignItems:"center",gap:"0.6rem"}}>{user.profileImage ? <img src={assetUrl(user.profileImage)} alt={user.name} style={{width:"32px",height:"32px",borderRadius:"8px",objectFit:"cover"}} /> : <span style={{display:"grid",width:"32px",height:"32px",placeItems:"center",borderRadius:"8px",background:"#e2eddd",color:"#35684c",fontSize:"0.62rem",fontWeight:700}}>{user.name.charAt(0)}</span>}<strong>{user.name}</strong></div></td><td>{user.email}</td><td>{user.phone || "-"}</td><td>{user.address || "-"}</td><td><button className="view-orders-button" onClick={() => setSelected(user)}><Icon name="eye"/><span>View Details</span></button></td></tr>)}</tbody></table></div>{!users.length && <p style={{ padding: 24, textAlign: "center" }}>{loading ? "Loading buyers..." : error || "No buyers registered."}</p>}</section>
  {selected && <div className="detail-overlay" role="dialog"><button className="detail-backdrop" onClick={() => setSelected(null)}/><section className="dashboard-card buyer-orders-panel"><div className="buyer-orders-header"><h2>{selected.name}&apos;s Orders</h2><button onClick={() => setSelected(null)}><Icon name="x"/></button></div><div className="buyer-order-stats"><div><span>Total Orders</span><strong>{selected.orders.length}</strong></div><div><span>Total Products</span><strong>{selected.orders.reduce((sum, o) => sum + o.items.length, 0)}</strong></div><div><span>Total Spent</span><strong>Rs {spent.toLocaleString("en-IN")}</strong></div></div><div className="table-scroll"><table><thead><tr><th>Order ID</th><th>Date</th><th>Products</th><th>Status</th><th>Total</th></tr></thead><tbody>{selected.orders.map((o) => <tr key={o._id}><td>{o.orderNumber}</td><td>{new Date(o.createdAt).toLocaleDateString()}</td><td>{o.items.length}</td><td><span className={`status ${o.status.toLowerCase()}`}>{o.status}</span></td><td>Rs {o.total.toLocaleString("en-IN")}</td></tr>)}</tbody></table></div></section></div>}</AdminShell>;
}

