"use client";
import { useState } from "react";
import { AdminShell, Icon } from "../components/admin-shell";
import { assetUrl, useAdminApi } from "../lib/api";
type Buyer = { id: string; name: string; email: string; phone: string; address: string; profileImage?: string; orders: Array<{ _id: string; orderNumber: string; createdAt: string; items: unknown[]; status: string; total: number }> };
export default function BuyerManagementPage() { const { data: users, loading, error } = useAdminApi<Buyer[]>("/admin/users?role=buyer", []); const [selected, setSelected] = useState<Buyer | null>(null); const [search, setSearch] = useState(""); const spent = selected?.orders.reduce((sum, o) => sum + o.total, 0) || 0;
  const query = search.trim().toLowerCase();
  const filteredUsers = users.filter((user) => !query || user.name.toLowerCase().includes(query) || user.email.toLowerCase().includes(query) || (user.phone || "").toLowerCase().includes(query));
  return <AdminShell title="User Management" subtitle="Manage registered users and view their order history."><section className="dashboard-card simple-users-card"><div className="simple-users-heading"><h2>All Users ({filteredUsers.length})</h2><label className="simple-users-search"><Icon name="search"/><input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search by name, email, or number..."/></label></div><div className="table-scroll"><table className="simple-users-table"><thead><tr><th>User</th><th>Email</th><th>Phone</th><th>Address</th><th/></tr></thead><tbody>{filteredUsers.map((user) => <tr key={user.id}><td><div style={{display:"flex",alignItems:"center",gap:"0.6rem"}}>{user.profileImage ? <img src={assetUrl(user.profileImage)} alt={user.name} style={{width:"32px",height:"32px",borderRadius:"8px",objectFit:"cover"}} /> : <span style={{display:"grid",width:"32px",height:"32px",placeItems:"center",borderRadius:"8px",background:"#e2eddd",color:"#35684c",fontSize:"0.62rem",fontWeight:700}}>{user.name.charAt(0)}</span>}<strong>{user.name}</strong></div></td><td>{user.email}</td><td>{user.phone || "-"}</td><td>{user.address || "-"}</td><td><button className="table-icon-button" onClick={() => setSelected(user)}><Icon name="eye"/></button></td></tr>)}</tbody></table></div>{!filteredUsers.length && <p style={{ padding: 24, textAlign: "center" }}>{loading ? "Loading buyers..." : error || (users.length ? "No users match your search." : "No buyers registered.")}</p>}</section>
  {selected && <div className="detail-overlay" role="dialog"><button className="detail-backdrop" onClick={() => setSelected(null)}/><section className="dashboard-card farmer-detail-panel"><div className="detail-header"><div className="detail-profile"><span>{selected.name.charAt(0).toUpperCase()}</span><div><h2>{selected.name}</h2><p>{selected.email}</p></div></div><button className="detail-close-button" onClick={() => setSelected(null)}><Icon name="x"/></button></div><dl className="detail-list"><div><dt>Email</dt><dd>{selected.email}</dd></div><div><dt>Phone</dt><dd>{selected.phone || "Not provided"}</dd></div><div><dt>Address</dt><dd>{selected.address || "Not provided"}</dd></div><div><dt>Total Orders</dt><dd>{selected.orders.length}</dd></div><div><dt>Total Products</dt><dd>{selected.orders.reduce((sum, o) => sum + o.items.length, 0)}</dd></div><div><dt>Total Spent</dt><dd>Rs {spent.toLocaleString("en-IN")}</dd></div></dl><div className="table-scroll"><table><thead><tr><th>Order ID</th><th>Date</th><th>Products</th><th>Status</th><th>Total</th></tr></thead><tbody>{selected.orders.map((o) => <tr key={o._id}><td>{o.orderNumber}</td><td>{new Date(o.createdAt).toLocaleDateString()}</td><td>{o.items.length}</td><td><span className={`status ${o.status.toLowerCase()}`}>{o.status}</span></td><td>Rs {o.total.toLocaleString("en-IN")}</td></tr>)}</tbody></table></div></section></div>}</AdminShell>;
}

